package main;
import com.toedter.calendar.JDateChooser;
import java.sql.PreparedStatement;
import utility.KoneksiDB;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.Format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * @author user
 */
public class Pesanan extends javax.swing.JFrame {
    private KoneksiDB DB = new KoneksiDB();
    private Statement stat = DB.stat;
    private ResultSet rs;
    private String query, id;
    
    public Pesanan() {
        initComponents();
        setLocationRelativeTo(null);
        tabel("Belum dibayar");
//        comboboxdb();
    }
    
    private void tabel(String status){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Id");
        tb.addColumn("Nama");
        tb.addColumn("No. Telp");
        tb.addColumn("Tgl Tiket");
        tb.addColumn("Wahana");
        tb.addColumn("Jumlah");
        tb.addColumn("Tgl Pesan");
        tbl_pesanan.setModel(tb);
        
        query = "SELECT * FROM tb_pesanan "
              + "JOIN tb_kategori ON (tb_pesanan.id_kategori = tb_kategori.id_kategori)"
              + "WHERE tb_pesanan.status = '"+status+"'";
        try {
            rs = stat.executeQuery(query); //rs = ResultSet <- hasil eksekusi query
            while (rs.next()) {
                tb.addRow(new Object[]{
                    rs.getString("id_pesanan"),
                    rs.getString("nama_pemesan"),
                    rs.getString("telp_pemesan"),
                    formatTglId(rs.getString("tanggal_tiket")),
                    rs.getString("nama"),
                    rs.getString("jumlah"),
                    formatTglId(rs.getString("tanggal_pesan"))
                });
            }
        } catch(SQLException e) {
            System.err.println(e.getMessage());
        }
    }    
    
    private String formatTglId(String ptgl){
        String tgl = ptgl.substring(8,10);
        String bulan = ptgl.substring(5,7);
        String tahun = ptgl.substring(0,4);
        return tgl+"-"+bulan+"-"+tahun;
    }
    
    private String formatTglEn(String ptgl){
        // 22-02-2023 to 2023-02-22
        String tgl = ptgl.split("-")[0];
        String bulan = ptgl.split("-")[1];
        String tahun = ptgl.split("-")[2];
        return tahun+"-"+bulan+"-"+tgl;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grup_status = new javax.swing.ButtonGroup();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pesanan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        rb_belumDibayar = new javax.swing.JRadioButton();
        rb_lunas = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Pesanan");

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        tbl_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama Pemesan", "Telp", "Tgl Tiket", "Wahana", "Jumlah", "Tgl Pesan"
            }
        ));
        tbl_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pesanan);

        jLabel1.setText("Status");

        grup_status.add(rb_belumDibayar);
        rb_belumDibayar.setSelected(true);
        rb_belumDibayar.setText("Belum dibayar");
        rb_belumDibayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_belumDibayarActionPerformed(evt);
            }
        });

        grup_status.add(rb_lunas);
        rb_lunas.setText("Lunas");
        rb_lunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_lunasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_belumDibayar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_lunas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hapus)
                    .addComponent(btn_edit)
                    .addComponent(jLabel1)
                    .addComponent(rb_belumDibayar)
                    .addComponent(rb_lunas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

         
    
    private void tbl_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pesananMouseClicked
//        int row = tableUser.getSelectedRow();
//        TableModel model = tableUser.getModel();
//        idpesanan = model.getValueAt(row, 0).toString();
//        jumlah.setText(model.getValueAt(row, 3).toString());
//        status.setText(model.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tbl_pesananMouseClicked

    private void rb_belumDibayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_belumDibayarActionPerformed
        tabel("Belum dibayar");
    }//GEN-LAST:event_rb_belumDibayarActionPerformed

    private void rb_lunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_lunasActionPerformed
        tabel("Lunas");
    }//GEN-LAST:event_rb_lunasActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        int bar = tbl_pesanan.getSelectedRow();
        if (bar == -1) JOptionPane.showMessageDialog(null, "Pilih baris data yang ingin diubah !");
        else {
            TableModel tabmode = tbl_pesanan.getModel();
            id = tabmode.getValueAt(bar, 0).toString();
            String nama = tabmode.getValueAt(bar, 1).toString();
            String telp = tabmode.getValueAt(bar, 2).toString();
            String str_tglTiket = formatTglEn(tabmode.getValueAt(bar, 3).toString());
            String wahana = tabmode.getValueAt(bar, 4).toString();
            String jumlah = tabmode.getValueAt(bar, 5).toString();
            
            JTextField tf_nama = new JTextField();
            JTextField tf_telp = new JTextField();
            JDateChooser dt_tglTiket = new JDateChooser();
            JComboBox cb_wahana = new JComboBox();            
            JTextField tf_jumlah = new JTextField();
            
            System.out.println(str_tglTiket);
            
            try {
                Date tglTiket = new SimpleDateFormat("yyyy-MM-dd").parse(str_tglTiket);
                dt_tglTiket.setDate(tglTiket);
            } catch(ParseException e){
                System.err.println(e.getMessage());
            }
            tf_nama.setText(nama);
            tf_telp.setText(telp);
            setOpsiWahana(cb_wahana);
            cb_wahana.setSelectedItem(wahana);
            tf_jumlah.setText(jumlah);

            Object[] fields = {
                "Nama :", tf_nama,
                "Telp :", tf_telp,
                "Tgl Tiket: ", dt_tglTiket,
                "Wahana :", cb_wahana,
                "Jumlah :", tf_jumlah
            };
            int ok = JOptionPane.showConfirmDialog(null, fields, "Ubah Pesanan",
                     JOptionPane.OK_CANCEL_OPTION);
            if (ok==0){
                Format formatter = new SimpleDateFormat("YYYY-MM-dd");
                str_tglTiket = formatter.format(dt_tglTiket.getDate());
                wahana = cb_wahana.getSelectedItem().toString();
                
                query = "UPDATE tb_pesanan SET "
                      + "nama_pemesan='"+tf_nama.getText()+"', telp_pemesan='"+tf_telp.getText()
                      + "', tanggal_tiket='"+str_tglTiket+"', id_kategori='"+getIdKategori(wahana)
                      + "', jumlah='"+tf_jumlah.getText()+"' "
                      + "WHERE id_pesanan='"+id+"'";
                try {
                    stat.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Berhasil Diubah");
                    tabel("Belum dibayar");
                } catch(SQLException e){
                    System.err.println(e.getMessage());
                }                
            }
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int bar = tbl_pesanan.getSelectedRow();
        if (bar == -1) JOptionPane.showMessageDialog(null, "Pilih baris data yang ingin diubah !");
        else {
            TableModel tabmode = tbl_pesanan.getModel();
            id = tabmode.getValueAt(bar, 0).toString();            
            if (cekIdPesanan(id)){
                int ok = JOptionPane.showConfirmDialog(null,
                        "id pesanan ini pada tabel penjualan juga akan ikut terhapus, Yakin ?",
                        "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
                if (ok==0){
                    String query2 = "DELETE FROM tb_penjualan WHERE id_pesanan ='"+id+"'";
                    query = "DELETE FROM tb_pesanan WHERE id_pesanan ='"+id+"'";
                    try {
                        stat.executeUpdate(query2);
                        stat.executeUpdate(query);
                        tabel("Belum dibayar");
                        JOptionPane.showMessageDialog(null, "berhasil dihapus");
                    } catch(SQLException e){
                        System.err.println(e.getMessage());
                    }
                }
            } else {
                query = "DELETE FROM tb_pesanan WHERE id_pesanan ='"+id+"'";
                try {
                    stat.executeUpdate(query);
                    tabel("Belum dibayar");
                    JOptionPane.showMessageDialog(null, "berhasil dihapus");
                } catch(SQLException e){
                    System.err.println(e.getMessage());
                }
            }            
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private boolean cekIdPesanan(String pid){
        query = "SELECT id_pesanan FROM tb_penjualan WHERE id_pesanan = '"+pid+"'";
        try {
            rs = stat.executeQuery(query);
            if (rs.next()) return true;
        } catch(SQLException e){
            System.err.println(e.getMessage());
        }
        return false;
    }
    
    private void setOpsiWahana(JComboBox pwahana){
        query = "SELECT * FROM tb_kategori";
        try {            
            rs = stat.executeQuery(query);
            while (rs.next()) pwahana.addItem(rs.getString(2));
        } catch(SQLException e){
            System.err.println(e.getMessage());
        }
    }
        
    private String getIdKategori(String pwahana){
        query = "SELECT id_kategori FROM tb_kategori "
              + "WHERE nama = '"+pwahana+"'";
        try {
            rs = stat.executeQuery(query);
            if (rs.next()) return rs.getString("id_kategori");
        } catch(SQLException e){
            System.err.println(e.getMessage());
        }
        return "";
    }

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.ButtonGroup grup_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_belumDibayar;
    private javax.swing.JRadioButton rb_lunas;
    private javax.swing.JTable tbl_pesanan;
    // End of variables declaration//GEN-END:variables
}
